
apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: smartpay

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      restartPolicy: Always

      containers:
        - name: backend

          image: 677078406480.dkr.ecr.ap-south-1.amazonaws.com/smartpay-backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: smartpay-secret
                  key: DB_HOST

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: smartpay-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartpay-secret
                  key: DB_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: smartpay-secret
                  key: DB_NAME

            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: smartpay-config
                  key: ENV      
