apiVersion: v1
kind: Secret

metadata:
  name: smartpay-secret
  namespace: smartpay

type: Opaque

stringData:
  DB_HOST: smartpay-mysql-rds.c900g2g8an4e.ap-south-1.rds.amazonaws.com
  DB_USER: admin
  DB_PASSWORD: Smartpay123
  DB_NAME: smartpaydb