name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Debug Repository Structure
      - name: Debug Files
        run: |
          echo "Current Directory:"
          pwd

          echo "Repository Files:"
          ls -la

          echo "Full Directory Structure:"
          find . -type f

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Frontend Docker Image
        run: |
          docker build -t smartpay-frontend ./frontend

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag smartpay-frontend:latest \
          677078406480.dkr.ecr.ap-south-1.amazonaws.com/smartpay-frontend:latest

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push \
          677078406480.dkr.ecr.ap-south-1.amazonaws.com/smartpay-frontend:latest

      # Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      # Configure kubeconfig for EKS
      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
          --region ap-south-1 \
          --name smartpay-cluster

      # Verify Kubernetes Files
      - name: Verify Kubernetes YAML Files
        run: |
          ls -la k8s

      # Deploy to EKS
      - name: Deploy Frontend to EKS
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      # Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc